name: CI

on: # yamllint disable-line rule:truthy
  # push:
  #   # branches:
  #   #   - main
  workflow_dispatch:

# env:
#   ACR_IMAGE_PATH_FRONTEND: ${{ secrets.ACR_LOGIN_SERVER }}/frontendmodule:1.0.${{ github.run_number }}-amd64
#   ACR_IMAGE_PATH_BACKEND: ${{ secrets.ACR_LOGIN_SERVER }}/backendmodule:1.0.${{ github.run_number }}-amd64

jobs:
  build:
    permissions:
      id-token: write
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          make install

      - name: Build backend docker image
        run: |
          IMAGE=iot-backend
          cd ./EdgeSolution/modules/BackendModule
          docker build -f Dockerfile.amd64 -t $IMAGE .
          echo "::set-output name=image::$IMAGE"

      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      # WARNING: The --cred-file flag is in preview and is subject to change.
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud components install docker-credential-gcr
          gcloud --quiet auth configure-docker
      - name: Generate build ID
        id: prep
        run: |
            env=prod
            sha=${GITHUB_SHA::8}
            ts=$(date +%Y%m%d%H%M%S)
            echo "::set-output name=BUILD_ID::${env}-${ts}-${sha}"
      - name: Build docker
        id: build
        run: |-
          PROJECT_ID=monitoring-378615
          GCR_IMAGE=gcr.io/$PROJECT_ID/iot-backend
          docker tag iot-backend $GCR_IMAGE
          docker push $GCR_IMAGE
          echo "::set-output name=image::$GCR_IMAGE"

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'iot-backend'
      #     cache-dir: '/var/lib/trivy'
      #     exit-code: '0'
      #     severity: 'MEDIUM,HIGH,CRITICAL,LOW'

      # - name: Run the Anchore Grype scan action
      #   uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      #   id: scan
      #   with:
      #     image: "iot-backend"
      #     fail-build: false
      #     acs-report-enable: true
      #     severity-cutoff: critical

      # - name: Upload vulnerability report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: grype
        continue-on-error: false
        run: |-
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          grype -h
          grype iot-backend

      - name: snyk test
        continue-on-error: true
        run: |-
          npm install snyk -g
          snyk auth e6b5719c-46fa-4dd7-8cf1-50ebd68923ae
          snyk container test iot-backend
          snyk container monitor --app-vulns iot-backend

      - name: Run Snyk to check Docker image for vulnerabilities
        # Snyk can be used to break the build when it detects vulnerabilities.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # More details in https://github.com/snyk/actions#getting-your-snyk-token
        # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: iot-backend
          args: --file=./EdgeSolution/modules/BackendModule/Dockerfile.amd64

      # - name: Build frontend docker image
      #   run: |
      #     IMAGE=iot-frontend
      #     cd ./EdgeSolution/modules/FrontendModule
      #     docker build -f Dockerfile.amd64 -t $IMAGE .
      #     echo "::set-output name=image::$IMAGE"

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'iot-frontend'
      #     cache-dir: '/var/lib/trivy'
      #     exit-code: '0'
      #     severity: 'MEDIUM,HIGH,CRITICAL,LOW'

      # - name: Run the Anchore Grype scan action
      #   uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      #   id: scan2
      #   with:
      #     image: "iot-backend"
      #     fail-build: false
      #     acs-report-enable: true
      #     severity-cutoff: critical

      # - name: Upload vulnerability report
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: ${{ steps.scan.outputs.sarif }}

      # - name: snyk test
      #   continue-on-error: true
      #   run: |-
      #      npm install snyk -g
      #      snyk auth e6b5719c-46fa-4dd7-8cf1-50ebd68923ae
      #      snyk container test iot-frontend --json-file-output=vuln.json
      
      # - name: Run Snyk to check Docker image for vulnerabilities
      #   # Snyk can be used to break the build when it detects vulnerabilities.
      #   # In this case we want to upload the issues to GitHub Code Scanning
      #   continue-on-error: true
      #   uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
      #   env:
      #   # In order to use the Snyk Action you will need to have a Snyk API token.
      #   # More details in https://github.com/snyk/actions#getting-your-snyk-token
      #   # or you can signup for free at https://snyk.io/login
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: iot-frontend
      #     args: --file=./EdgeSolution/modules/BackendModule/Dockerfile.amd64
      # # - name: Push backend docker image
      # #   run: |
      # #     docker push ${{env.ACR_IMAGE_PATH_BACKEND}}

      # # - name: Push frontend docker image
      # #   run: |
      # #     docker push ${{env.ACR_IMAGE_PATH_FRONTEND}}
